# Generated by Django 3.1.7 on 2021-03-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_auto_20210305_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.IntegerField(verbose_name='路線')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='列車名'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='sex',
        ),
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.ManyToManyField(choices=[(1, '東海道'), (2, '山陽'), (3, '東北'), (4, '上越'), (5, '山形'), (6, '秋田'), (7, '北陸'), (8, '九州'), (9, '北海道')], default=1, to='trains.Route', verbose_name='所属路線'),
        ),
    ]
