# Generated by Django 3.1.7 on 2021-03-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_auto_20210308_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_name',
            field=models.CharField(default='', max_length=20, verbose_name='路線名'),
        ),
    ]
