# Generated by Django 3.1.7 on 2021-03-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0005_auto_20210308_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sex',
            new_name='route',
        ),
    ]
