# Generated by Django 3.1.7 on 2021-03-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0006_auto_20210308_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='age',
        ),
        migrations.AddField(
            model_name='item',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='画像'),
        ),
    ]
